package com.mzy.entity;

import java.util.Date;

/**
 * tag
 *
 * @author bianj
 * @version 1.0.0 2020-08-20
 */
public class Tag implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5999018513420831123L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** blogCount */
    private Integer blogCount;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     *
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     *
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取blogCount
     *
     * @return blogCount
     */
    public Integer getBlogCount() {
        return this.blogCount;
    }

    /**
     * 设置blogCount
     *
     * @param blogCount
     */
    public void setBlogCount(Integer blogCount) {
        this.blogCount = blogCount;
    }

    /**
     * 获取createTime
     *
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     *
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
