package com.mzy.entity;

import java.util.Date;

/**
 * user
 *
 * @author bianj
 * @version 1.0.0 2020-08-20
 */
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -9096149128018368590L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** password */
    private String password;

    /** icon */
    private String icon;

    /** admin */
    private Integer admin;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     *
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     *
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取password
     *
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置password
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取icon
     *
     * @return icon
     */
    public String getIcon() {
        return this.icon;
    }

    /**
     * 设置icon
     *
     * @param icon
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * 获取admin
     *
     * @return admin
     */
    public Integer getAdmin() {
        return this.admin;
    }

    /**
     * 设置admin
     *
     * @param admin
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    /**
     * 获取createTime
     *
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     *
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
